[package]
name                = "saa-schema"
description         = "Macros and serialization utlities for various blockchain based virtual machines"
edition             = { workspace = true }
authors             = { workspace = true }
version             = { workspace = true }
license             = { workspace = true }
repository          = { workspace = true }

[dependencies]
saa-macros-proto    = { workspace = true }
serde               = { workspace = true } 

# Substrate
scale               = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
# CosmWasm
schemars            = { workspace = true, optional = true }
# Solana
borsh               = { workspace = true, optional = true }

strum               = { workspace = true, optional = true }
strum_macros       = { workspace = true, optional = true }


[features]
default        = ["std"]
solana         = ["dep:borsh",                   "saa-macros-proto/solana"    ]
substrate      = ["dep:scale", "dep:scale-info", "saa-macros-proto/substrate" ]
cosmwasm       = ["dep:schemars",                "saa-macros-proto/cosmwasm"  ]
std            = ["scale?/std", "scale-info?/std"                             ]
session        = ["saa-macros-proto/session", "dep:strum_macros", "dep:strum" ]