[package]
name                = "saa-schema"
description         = "Macros and serialization utlities for various blockchain based virtual machines"
edition             = { workspace = true }
authors             = { workspace = true }
version             = { workspace = true }
license             = { workspace = true }
repository          = { workspace = true }

[dependencies]
saa-proto-core      = { workspace = true  }
saa-proto-wasm      = { workspace = true, optional = true }
#saa-proto-session   = { workspace = true, optional = true }

thiserror           = { version = "2.0.12", default-features = false }


serde               = { workspace = true } 

# Substrate
scale               = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
# CosmWasm
schemars            = { workspace = true, optional = true }
# Solana
borsh               = { workspace = true, optional = true }

strum               = { workspace = true }
strum_macros        = { workspace = true }
cosmwasm-schema     = { workspace = true, optional = true }

[features]
default        = ["std"]
solana         = ["dep:borsh",                     ]
substrate      = ["dep:scale", "dep:scale-info"    ]
std            = ["scale?/std", "scale-info?/std",                             ]
cosmwasm       = ["dep:schemars", "dep:cosmwasm-schema", "saa-proto-wasm", "std"     ]
session        = [  ]