[package]
name        = "saa-auth"
description = "Custom credentials built on top of curves and their verification logic for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
hex                     = "0.4.3"
sha2                    = { workspace = true } 
bech32                  = { workspace = true }
base64                  = { workspace = true }

saa-common              = { workspace = true }
saa-schema              = { workspace = true }
saa-curves              = { workspace = true }

schemars                = { workspace = true, optional = true }
serde                   = { workspace = true, optional = true }


[features]
default = [
    "std"
]
std = [
    "saa-curves/std",
    "bech32/std"
]
native = [
    "saa-curves/native",
]
cosmwasm = [
    "saa-curves/cosmwasm",
    "wasm"
]
cosmwasm_1 = [
    "saa-curves/cosmwasm_1",
    "wasm",
]
wasm  = ["dep:serde", "dep:schemars"]
