[package]
name        = "saa-auth"
description = "Custom credentials built on top of curves and their verification logic for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
hex                     = "0.4.3"
sha2                    = { workspace = true } 
bech32                  = { workspace = true }
base64                  = { workspace = true }

saa-common              = { workspace = true }
saa-schema              = { workspace = true }
saa-curves              = { workspace = true }

scale                   = { workspace = true, optional = true }
scale-info              = { workspace = true, optional = true }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true, optional = true }
serde                   = { workspace = true }

[dev-dependencies]
cosmwasm-std            = { workspace = true, features = ["staking"]}
saa-auth                = { path = ".", features = ["cosmwasm"] }
saa-curves              = { workspace = true, features = ["cosmwasm"] }
base64-url              = "3.0.0"

[features]
default = [
    "std"
]
std = [
    "saa-curves/std",
    "bech32/std",
    "scale?/std",
    "scale-info?/std",
]
native = [
    "saa-curves/native",
]
solana = [
    "dep:borsh",
    "saa-curves/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-curves/substrate",
]
cosmwasm = [
    "saa-curves/cosmwasm",
    "wasm"
]
cosmwasm_1 = [
    "saa-curves/cosmwasm_1",
    "wasm",
]
injective = [
    "saa-common/injective",
    "cosmwasm"
]
wasm  = []
utils = []
