[package]
name        = "saa-auth"
description = "Custom credentials built on top of curves and their verification logic for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
hex                 = { version = "0.4.3", optional = true, default-features = false }
serde               = { workspace = true,  optional = true }
saa-crypto          = { workspace = true }
saa-common          = { workspace = true }
saa-schema          = { workspace = true }

[features]
default             =   ["std"]
std                 =   ["saa-crypto/std",     "hex?/std"]
eth_personal        =   ["saa-crypto/ethereum", "dep:hex"]
eth_typed_data      =   ["saa-crypto/ethereum", "dep:hex", "dep:serde"]
native              =   ["saa-crypto/native"   ] 
cosmwasm            =   ["saa-crypto/cosmwasm"]
cosmos              =   []
