[package]
name        = "saa-passkeys"
description = "Custom credentials built on top of curves and their verification logic for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[dependencies]
serde               = { workspace = true, optional = true}
saa-common          = { workspace = true }
saa-schema          = { workspace = true }
saa-crypto          = { workspace = true }

[features]
default             =   ["std"]
passkeys            =   ["dep:serde"]
secp256r1           =   [     ]

cosmwasm            =   [      ]
no_api_r1           =   ["saa-crypto/secp256r1"]
native              =   ["saa-crypto/native"] 
std                 =   ["saa-crypto/std"]
