[package]
name        = "saa-proto-substrate"
description = "Procedural macros of saa-schema for wasm"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1"

[dependencies.quote]
version = "1"

[dependencies.syn]
version = "1"
features = [
    "full",
    "printing",
    "extra-traits",
]
[features]
std = []