[package]
name        = "saa-curves"
description = "Cryptographic curves for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }


[dependencies]
saa-schema  = { workspace = true }
saa-common  = { workspace = true }
saa-crypto  = { workspace = true }


[features]
default      =   ["std"]
ed25519      =   [     ]
secp256k1    =   [     ]

std          =   ["saa-crypto/std",     ]
native       =   ["saa-crypto/native"   ]
cosmwasm     =   []
