[package]
name        = "saa-curves"
description = "Cryptographic curves for smart account auth"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }


[dependencies]
bech32                  = { workspace = true }
saa-common              = { workspace = true }
saa-schema              = { workspace = true }


scale                   = { workspace = true, optional = true  }
scale-info              = { workspace = true, optional = true  }

borsh                   = { workspace = true, optional = true }
schemars                = { workspace = true }
serde                   = { workspace = true }

digest                  = { version = "0.10.7", default-features = false }
p256                    = { version = "0.13.2" }


[features]
default = [
    "std"
]
std = [
    "scale?/std",
    "scale-info?/std",
    "saa-common/std",
]
native = [
    "saa-common/native",
]
solana = [
    "dep:borsh",
    "saa-common/solana",
]
substrate = [
    "dep:scale",
    "dep:scale-info",
    "saa-common/substrate",
]
cosmwasm = [
    "saa-common/cosmwasm",
    "wasm"
]
cosmwasm_1 = [
    "saa-common/cosmwasm_1",
    "wasm",
]
wasm  = []
